# Generated by Django 3.2 on 2022-07-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20220716_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
