# Generated by Django 3.2 on 2022-07-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherlinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
